GET http://0.0.0.0:8000/api/v1/contact

###
POST http://0.0.0.0:8000/api/v1/contact/
content-type: application/json

{
    "name": "Contact Name",
    "phone": 5551996660181,
    "email": "contact@example.com"
}

###
GET http://0.0.0.0:8000/api/v1/contact

###
DELETE http://localhost:8000/api/v1/contact/2/

###
GET https://viacep.com.br/ws/66666666/json/